version: '3'
services:
  php:
    image: php:8.0-fpm
    command:
      - /bin/sh
      - -c
      - |
          docker-php-ext-install mysqli
          echo "extension installed.....starting php-fpm........................................"
          php-fpm
    volumes:
      - './src:/var/www/html'

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './src:/var/www/html'
      - './docker/nginx:/etc/nginx/conf.d'

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - './dbs:/docker-entrypoint-initdb.d'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=egzaminy
